### ISSUE TITLE
'active' class disappears when a hashtag is added

### ISSUE THREAD

**Issue by mskims** [ridi/cms-ui#46]
Hello, 

Sometimes, URL can have the hashtag depending on the user's interaction, but at that moment, the added `MenuItem`'s `active` class is disappeared. 

I think the `isActiveUrl` function which decides whether to add `active` class is the cause of this issue. 

I tried to fix this bug myself and make a pull request, but i think it's better to let you know first by opening the issue. below is the related code block.

Thanks!:

https://github.com/ridi/cms-ui/blob/77cdcabdec4bc363eaf71857475e019f4a9b2881/src/components/Menu/TreeMenu/index.js#L14-L19

**Comment by krazijames** [comment]
@mskims 
This was originally because of the menus that have the same paths and different hashtags from each other. But after I checked them, I noticed that they have not been exposed in UI at all. (Maybe those menus are not intended to be used in UI.)

So it will be OK to update `isActiveUrl()` as you mentioned. And it is always welcome to make a pull request! :sparkles: 

Thank you! :smile:
